using System;
using System.Collections.Generic;
using System.Text;

namespace BelugaMobile.Db
{
    public class PYTABLE
    {
	    public int   iIndex;//索引值
	    public string strPY;//拼音值

        public PYTABLE(int index, string pinyin)
        {
            iIndex = index;
            strPY = pinyin;
        }
    }

    class Han2Pinyin
    {
        private static PYTABLE[] m_pyTable =
                        {
	                        new PYTABLE(-20319,"a"),
	                        new PYTABLE(-20317,"ai"),
	                        new PYTABLE(-20304,"an"),
	                        new PYTABLE(-20295,"ang"),
	                        new PYTABLE(-20292,"ao"),
	                        new PYTABLE(-20283,"ba"),
	                        new PYTABLE(-20265,"bai"),
	                        new PYTABLE(-20257,"ban"),
	                        new PYTABLE(-20242,"bang"),
	                        new PYTABLE(-20230,"bao"),
	                        new PYTABLE(-20051,"bei"),
	                        new PYTABLE(-20036,"ben"),
	                        new PYTABLE(-20032,"beng"),
	                        new PYTABLE(-20026,"bi"),
	                        new PYTABLE(-20002,"bian"),
	                        new PYTABLE(-19990,"biao"),
	                        new PYTABLE(-19986,"bie"),
	                        new PYTABLE(-19982,"bin"),
	                        new PYTABLE(-19976,"bing"),
	                        new PYTABLE(-19805,"bo"),
	                        new PYTABLE(-19784,"bu"),
	                        new PYTABLE(-19775,"ca"),
	                        new PYTABLE(-19774,"cai"),
	                        new PYTABLE(-19763,"can"),
	                        new PYTABLE(-19756,"cang"),
	                        new PYTABLE(-19751,"cao"),
	                        new PYTABLE(-19746,"ce"),
	                        new PYTABLE(-19741,"ceng"),
	                        new PYTABLE(-19739,"cha"),
	                        new PYTABLE(-19728,"chai"),
	                        new PYTABLE(-19725,"chan"),
	                        new PYTABLE(-19715,"chang"),
	                        new PYTABLE(-19540,"chao"),
	                        new PYTABLE(-19531,"che"),
	                        new PYTABLE(-19525,"chen"),
	                        new PYTABLE(-19515,"cheng"),
	                        new PYTABLE(-19500,"chi"),
	                        new PYTABLE(-19484,"chong"),
	                        new PYTABLE(-19479,"chou"),
	                        new PYTABLE(-19467,"chu"),
	                        new PYTABLE(-19289,"chuai"),
	                        new PYTABLE(-19288,"chuan"),
	                        new PYTABLE(-19281,"chuang"),
	                        new PYTABLE(-19275,"chui"),
	                        new PYTABLE(-19270,"chun"),
	                        new PYTABLE(-19263,"chuo"),
	                        new PYTABLE(-19261,"ci"),
	                        new PYTABLE(-19249,"cong"),
	                        new PYTABLE(-19243,"cou"),
	                        new PYTABLE(-19242,"cu"),
	                        new PYTABLE(-19238,"cuan"),
	                        new PYTABLE(-19235,"cui"),
	                        new PYTABLE(-19227,"cun"),
	                        new PYTABLE(-19224,"cuo"),
	                        new PYTABLE(-19218,"da"),
	                        new PYTABLE(-19212,"dai"),
	                        new PYTABLE(-19038,"dan"),
	                        new PYTABLE(-19023,"dang"),
	                        new PYTABLE(-19018,"dao"),
	                        new PYTABLE(-19006,"de"),
	                        new PYTABLE(-19003,"deng"),
	                        new PYTABLE(-18996,"di"),
	                        new PYTABLE(-18977,"dian"),
	                        new PYTABLE(-18961,"diao"),
	                        new PYTABLE(-18952,"die"),
	                        new PYTABLE(-18783,"ding"),
	                        new PYTABLE(-18774,"diu"),
	                        new PYTABLE(-18773,"dong"),
	                        new PYTABLE(-18763,"dou"),
	                        new PYTABLE(-18756,"du"),
	                        new PYTABLE(-18741,"duan"),
	                        new PYTABLE(-18735,"dui"),
	                        new PYTABLE(-18731,"dun"),
	                        new PYTABLE(-18722,"duo"),
	                        new PYTABLE(-18710,"e"),
	                        new PYTABLE(-18697,"en"),
	                        new PYTABLE(-18696,"er"),
	                        new PYTABLE(-18526,"fa"),
	                        new PYTABLE(-18518,"fan"),
	                        new PYTABLE(-18501,"fang"),
	                        new PYTABLE(-18490,"fei"),
	                        new PYTABLE(-18478,"fen"),
	                        new PYTABLE(-18463,"feng"),
	                        new PYTABLE(-18448,"fo"),
	                        new PYTABLE(-18447,"fou"),
	                        new PYTABLE(-18446,"fu"),
	                        new PYTABLE(-18239,"ga"),
	                        new PYTABLE(-18237,"gai"),
	                        new PYTABLE(-18231,"gan"),
	                        new PYTABLE(-18220,"gang"),
	                        new PYTABLE(-18211,"gao"),
	                        new PYTABLE(-18201,"ge"),
	                        new PYTABLE(-18184,"gei"),
	                        new PYTABLE(-18183,"gen"),
	                        new PYTABLE(-18181,"geng"),
	                        new PYTABLE(-18012,"gong"),
	                        new PYTABLE(-17997,"gou"),
	                        new PYTABLE(-17988,"gu"),
	                        new PYTABLE(-17970,"gua"),
	                        new PYTABLE(-17964,"guai"),
	                        new PYTABLE(-17961,"guan"),
	                        new PYTABLE(-17950,"guang"),
	                        new PYTABLE(-17947,"gui"),
	                        new PYTABLE(-17931,"gun"),
	                        new PYTABLE(-17928,"guo"),
	                        new PYTABLE(-17922,"ha"),
	                        new PYTABLE(-17759,"hai"),
	                        new PYTABLE(-17752,"han"),
	                        new PYTABLE(-17733,"hang"),
	                        new PYTABLE(-17730,"hao"),
	                        new PYTABLE(-17721,"he"),
	                        new PYTABLE(-17703,"hei"),
	                        new PYTABLE(-17701,"hen"),
	                        new PYTABLE(-17697,"heng"),
	                        new PYTABLE(-17692,"hong"),
	                        new PYTABLE(-17683,"hou"),
	                        new PYTABLE(-17676,"hu"),
	                        new PYTABLE(-17496,"hua"),
	                        new PYTABLE(-17487,"huai"),
	                        new PYTABLE(-17482,"huan"),
	                        new PYTABLE(-17468,"huang"),
	                        new PYTABLE(-17454,"hui"),
	                        new PYTABLE(-17433,"hun"),
	                        new PYTABLE(-17427,"huo"),
	                        new PYTABLE(-17417,"ji"),
	                        new PYTABLE(-17202,"jia"),
	                        new PYTABLE(-17185,"jian"),
	                        new PYTABLE(-16983,"jiang"),
	                        new PYTABLE(-16970,"jiao"),
	                        new PYTABLE(-16942,"jie"),
	                        new PYTABLE(-16915,"jin"),
	                        new PYTABLE(-16733,"jing"),
	                        new PYTABLE(-16708,"jiong"),
	                        new PYTABLE(-16706,"jiu"),
	                        new PYTABLE(-16689,"ju"),
	                        new PYTABLE(-16664,"juan"),
	                        new PYTABLE(-16657,"jue"),
	                        new PYTABLE(-16647,"jun"),
	                        new PYTABLE(-16474,"ka"),
	                        new PYTABLE(-16470,"kai"),
	                        new PYTABLE(-16465,"kan"),
	                        new PYTABLE(-16459,"kang"),
	                        new PYTABLE(-16452,"kao"),
	                        new PYTABLE(-16448,"ke"),
	                        new PYTABLE(-16433,"ken"),
	                        new PYTABLE(-16429,"keng"),
	                        new PYTABLE(-16427,"kong"),
	                        new PYTABLE(-16423,"kou"),
	                        new PYTABLE(-16419,"ku"),
	                        new PYTABLE(-16412,"kua"),
	                        new PYTABLE(-16407,"kuai"),
	                        new PYTABLE(-16403,"kuan"),
	                        new PYTABLE(-16401,"kuang"),
	                        new PYTABLE(-16393,"kui"),
	                        new PYTABLE(-16220,"kun"),
	                        new PYTABLE(-16216,"kuo"),
	                        new PYTABLE(-16212,"la"),
	                        new PYTABLE(-16205,"lai"),
	                        new PYTABLE(-16202,"lan"),
	                        new PYTABLE(-16187,"lang"),
	                        new PYTABLE(-16180,"lao"),
	                        new PYTABLE(-16171,"le"),
	                        new PYTABLE(-16169,"lei"),
	                        new PYTABLE(-16158,"leng"),
	                        new PYTABLE(-16155,"li"),
	                        new PYTABLE(-15959,"lia"),
	                        new PYTABLE(-15958,"lian"),
	                        new PYTABLE(-15944,"liang"),
	                        new PYTABLE(-15933,"liao"),
	                        new PYTABLE(-15920,"lie"),
	                        new PYTABLE(-15915,"lin"),
	                        new PYTABLE(-15903,"ling"),
	                        new PYTABLE(-15889,"liu"),
	                        new PYTABLE(-15878,"long"),
	                        new PYTABLE(-15707,"lou"),
	                        new PYTABLE(-15701,"lu"),
	                        new PYTABLE(-15681,"lv"),
	                        new PYTABLE(-15667,"luan"),
	                        new PYTABLE(-15661,"lue"),
	                        new PYTABLE(-15659,"lun"),
	                        new PYTABLE(-15652,"luo"),
	                        new PYTABLE(-15640,"ma"),
	                        new PYTABLE(-15631,"mai"),
	                        new PYTABLE(-15625,"man"),
	                        new PYTABLE(-15454,"mang"),
	                        new PYTABLE(-15448,"mao"),
	                        new PYTABLE(-15436,"me"),
	                        new PYTABLE(-15435,"mei"),
	                        new PYTABLE(-15419,"men"),
	                        new PYTABLE(-15416,"meng"),
	                        new PYTABLE(-15408,"mi"),
	                        new PYTABLE(-15394,"mian"),
	                        new PYTABLE(-15385,"miao"),
	                        new PYTABLE(-15377,"mie"),
	                        new PYTABLE(-15375,"min"),
	                        new PYTABLE(-15369,"ming"),
	                        new PYTABLE(-15363,"miu"),
	                        new PYTABLE(-15362,"mo"),
	                        new PYTABLE(-15183,"mou"),
	                        new PYTABLE(-15180,"mu"),
	                        new PYTABLE(-15165,"na"),
	                        new PYTABLE(-15158,"nai"),
	                        new PYTABLE(-15153,"nan"),
	                        new PYTABLE(-15150,"nang"),
	                        new PYTABLE(-15149,"nao"),
	                        new PYTABLE(-15144,"ne"),
	                        new PYTABLE(-15143,"nei"),
	                        new PYTABLE(-15141,"nen"),
	                        new PYTABLE(-15140,"neng"),
	                        new PYTABLE(-15139,"ni"),
	                        new PYTABLE(-15128,"nian"),
	                        new PYTABLE(-15121,"niang"),
	                        new PYTABLE(-15119,"niao"),
	                        new PYTABLE(-15117,"nie"),
	                        new PYTABLE(-15110,"nin"),
	                        new PYTABLE(-15109,"ning"),
	                        new PYTABLE(-14941,"niu"),
	                        new PYTABLE(-14937,"nong"),
	                        new PYTABLE(-14933,"nu"),
	                        new PYTABLE(-14930,"nv"),
	                        new PYTABLE(-14929,"nuan"),
	                        new PYTABLE(-14928,"nue"),
	                        new PYTABLE(-14926,"nuo"),
	                        new PYTABLE(-14922,"o"),
	                        new PYTABLE(-14921,"ou"),
	                        new PYTABLE(-14914,"pa"),
	                        new PYTABLE(-14908,"pai"),
	                        new PYTABLE(-14902,"pan"),
	                        new PYTABLE(-14894,"pang"),
	                        new PYTABLE(-14889,"pao"),
	                        new PYTABLE(-14882,"pei"),
	                        new PYTABLE(-14873,"pen"),
	                        new PYTABLE(-14871,"peng"),
	                        new PYTABLE(-14857,"pi"),
	                        new PYTABLE(-14678,"pian"),
	                        new PYTABLE(-14674,"piao"),
	                        new PYTABLE(-14670,"pie"),
	                        new PYTABLE(-14668,"pin"),
	                        new PYTABLE(-14663,"ping"),
	                        new PYTABLE(-14654,"po"),
	                        new PYTABLE(-14645,"pu"),
	                        new PYTABLE(-14630,"qi"),
	                        new PYTABLE(-14594,"qia"),
	                        new PYTABLE(-14429,"qian"),
	                        new PYTABLE(-14407,"qiang"),
	                        new PYTABLE(-14399,"qiao"),
	                        new PYTABLE(-14384,"qie"),
	                        new PYTABLE(-14379,"qin"),
	                        new PYTABLE(-14368,"qing"),
	                        new PYTABLE(-14355,"qiong"),
	                        new PYTABLE(-14353,"qiu"),
	                        new PYTABLE(-14345,"qu"),
	                        new PYTABLE(-14170,"quan"),
	                        new PYTABLE(-14159,"que"),
	                        new PYTABLE(-14151,"qun"),
	                        new PYTABLE(-14149,"ran"),
	                        new PYTABLE(-14145,"rang"),
	                        new PYTABLE(-14140,"rao"),
	                        new PYTABLE(-14137,"re"),
	                        new PYTABLE(-14135,"ren"),
	                        new PYTABLE(-14125,"reng"),
	                        new PYTABLE(-14123,"ri"),
	                        new PYTABLE(-14122,"rong"),
	                        new PYTABLE(-14112,"rou"),
	                        new PYTABLE(-14109,"ru"),
	                        new PYTABLE(-14099,"ruan"),
	                        new PYTABLE(-14097,"rui"),
	                        new PYTABLE(-14094,"run"),
	                        new PYTABLE(-14092,"ruo"),
	                        new PYTABLE(-14090,"sa"),
	                        new PYTABLE(-14087,"sai"),
	                        new PYTABLE(-14083,"san"),
	                        new PYTABLE(-13917,"sang"),
	                        new PYTABLE(-13914,"sao"),
	                        new PYTABLE(-13910,"se"),
	                        new PYTABLE(-13907,"sen"),
	                        new PYTABLE(-13906,"seng"),
	                        new PYTABLE(-13905,"sha"),
	                        new PYTABLE(-13896,"shai"),
	                        new PYTABLE(-13894,"shan"),
	                        new PYTABLE(-13878,"shang"),
	                        new PYTABLE(-13870,"shao"),
	                        new PYTABLE(-13859,"she"),
	                        new PYTABLE(-13847,"shen"),
	                        new PYTABLE(-13831,"sheng"),
	                        new PYTABLE(-13658,"shi"),
	                        new PYTABLE(-13611,"shou"),
	                        new PYTABLE(-13601,"shu"),
	                        new PYTABLE(-13406,"shua"),
	                        new PYTABLE(-13404,"shuai"),
	                        new PYTABLE(-13400,"shuan"),
	                        new PYTABLE(-13398,"shuang"),
	                        new PYTABLE(-13395,"shui"),
	                        new PYTABLE(-13391,"shun"),
	                        new PYTABLE(-13387,"shuo"),
	                        new PYTABLE(-13383,"si"),
	                        new PYTABLE(-13367,"song"),
	                        new PYTABLE(-13359,"sou"),
	                        new PYTABLE(-13356,"su"),
	                        new PYTABLE(-13343,"suan"),
	                        new PYTABLE(-13340,"sui"),
	                        new PYTABLE(-13329,"sun"),
	                        new PYTABLE(-13326,"suo"),
	                        new PYTABLE(-13318,"ta"),
	                        new PYTABLE(-13147,"tai"),
	                        new PYTABLE(-13138,"tan"),
	                        new PYTABLE(-13120,"tang"),
	                        new PYTABLE(-13107,"tao"),
	                        new PYTABLE(-13096,"te"),
	                        new PYTABLE(-13095,"teng"),
	                        new PYTABLE(-13091,"ti"),
	                        new PYTABLE(-13076,"tian"),
	                        new PYTABLE(-13068,"tiao"),
	                        new PYTABLE(-13063,"tie"),
	                        new PYTABLE(-13060,"ting"),
	                        new PYTABLE(-12888,"tong"),
	                        new PYTABLE(-12875,"tou"),
	                        new PYTABLE(-12871,"tu"),
	                        new PYTABLE(-12860,"tuan"),
	                        new PYTABLE(-12858,"tui"),
	                        new PYTABLE(-12852,"tun"),
	                        new PYTABLE(-12849,"tuo"),
	                        new PYTABLE(-12838,"wa"),
	                        new PYTABLE(-12831,"wai"),
	                        new PYTABLE(-12829,"wan"),
	                        new PYTABLE(-12812,"wang"),
	                        new PYTABLE(-12802,"wei"),
	                        new PYTABLE(-12607,"wen"),
	                        new PYTABLE(-12597,"weng"),
	                        new PYTABLE(-12594,"wo"),
	                        new PYTABLE(-12585,"wu"),
	                        new PYTABLE(-12556,"xi"),
	                        new PYTABLE(-12359,"xia"),
	                        new PYTABLE(-12346,"xian"),
	                        new PYTABLE(-12320,"xiang"),
	                        new PYTABLE(-12300,"xiao"),
	                        new PYTABLE(-12120,"xie"),
	                        new PYTABLE(-12099,"xin"),
	                        new PYTABLE(-12089,"xing"),
	                        new PYTABLE(-12074,"xiong"),
	                        new PYTABLE(-12067,"xiu"),
	                        new PYTABLE(-12058,"xu"),
	                        new PYTABLE(-12039,"xuan"),
	                        new PYTABLE(-11867,"xue"),
	                        new PYTABLE(-11861,"xun"),
	                        new PYTABLE(-11847,"ya"),
	                        new PYTABLE(-11831,"yan"),
	                        new PYTABLE(-11798,"yang"),
	                        new PYTABLE(-11781,"yao"),
	                        new PYTABLE(-11604,"ye"),
	                        new PYTABLE(-11589,"yi"),
	                        new PYTABLE(-11536,"yin"),
	                        new PYTABLE(-11358,"ying"),
	                        new PYTABLE(-11340,"yo"),
	                        new PYTABLE(-11339,"yong"),
	                        new PYTABLE(-11324,"you"),
	                        new PYTABLE(-11303,"yu"),
	                        new PYTABLE(-11097,"yuan"),
	                        new PYTABLE(-11077,"yue"),
	                        new PYTABLE(-11067,"yun"),
	                        new PYTABLE(-11055,"za"),
	                        new PYTABLE(-11052,"zai"),
	                        new PYTABLE(-11045,"zan"),
	                        new PYTABLE(-11041,"zang"),
	                        new PYTABLE(-11038,"zao"),
	                        new PYTABLE(-11024,"ze"),
	                        new PYTABLE(-11020,"zei"),
	                        new PYTABLE(-11019,"zen"),
	                        new PYTABLE(-11018,"zeng"),
	                        new PYTABLE(-11014,"zha"),
	                        new PYTABLE(-10838,"zhai"),
	                        new PYTABLE(-10832,"zhan"),
	                        new PYTABLE(-10815,"zhang"),
	                        new PYTABLE(-10800,"zhao"),
	                        new PYTABLE(-10790,"zhe"),
	                        new PYTABLE(-10780,"zhen"),
	                        new PYTABLE(-10764,"zheng"),
	                        new PYTABLE(-10587,"zhi"),
	                        new PYTABLE(-10544,"zhong"),
	                        new PYTABLE(-10533,"zhou"),
	                        new PYTABLE(-10519,"zhu"),
	                        new PYTABLE(-10331,"zhua"),
	                        new PYTABLE(-10329,"zhuai"),
	                        new PYTABLE(-10328,"zhuan"),
	                        new PYTABLE(-10322,"zhuang"),
	                        new PYTABLE(-10315,"zhui"),
	                        new PYTABLE(-10309,"zhun"),
	                        new PYTABLE(-10307,"zhuo"),
	                        new PYTABLE(-10296,"zi"),
	                        new PYTABLE(-10281,"zong"),
	                        new PYTABLE(-10274,"zou"),
	                        new PYTABLE(-10270,"zu"),
	                        new PYTABLE(-10262,"zuan"),
	                        new PYTABLE(-10260,"zui"),
	                        new PYTABLE(-10256,"zun"),
	                        new PYTABLE(-10254,"zuo"),
	                        new PYTABLE(-10247,"zz")
                        };

        private static string GetPYbyChar(int chr)
        {
	        // 检查是否为ASCII字符
	        if (chr>0 && chr<160)
	        {
                return string.Format("{1}", chr);
	        }

	        // 无效字符(不在拼音数据范围)
	        if (chr<-20319 || chr>-10247)
	        {
		        return "";
	        }

	        // 根据索引表查找拼音(遍历算法-较慢)
	        for(int iLoop=m_pyTable.Length - 1; iLoop>=0; iLoop--)
	        {
		        if (m_pyTable[iLoop].iIndex <= chr)
		        {
			        return m_pyTable[iLoop].strPY;
		        }
	        }

            return "";
        }

        public static string Chinese2PY(string hz)
        {
	        int   iValue;
	        char  nFirst;
            char  nSecond;
	        string pinyin = "";

            for (int iLoop = 0; iLoop < hz.Length; iLoop++)
	        {
                nFirst = hz[iLoop];
		        if (nFirst > 160)
		        {
			        iLoop++;
                    nSecond = hz[iLoop];

			        // 赋值索引
			        iValue = nFirst * 256 + nSecond - 65536;
		        }
		        else
		        {
			        // 赋值索引(ASCII字符)
			        iValue = nFirst;
		        }

		        // 取得PY
                pinyin = string.Concat(pinyin, GetPYbyChar(iValue));
	        }

            return pinyin;
        }
    }
}
