alter table ContactTag drop constraint FK7F280B7A39AFF238;
drop table ContactTag;
drop table ContactUser;
drop table LOG;
drop table PhoneDistrict;
drop table Weather;
create table ContactTag (id char(32) not null, version int8 not null, name varchar(64) not null, logo varchar(128) not null, createTime timestamp not null, tagOrder int4 not null, deleteFlag bool not null, createUser varchar(255) not null, remark varchar(2000), primary key (id));
create table ContactUser (id char(32) not null, version int8 not null, logingName varchar(64) not null unique, registerTime timestamp not null, mobile varchar(64) not null unique, lastLoginTime timestamp, lastLoginIp varchar(64), remark varchar(2000), primary key (id));
create table LOG (ID varchar(255) not null, VERSION int8 not null, HANDLE varchar(20), INFOCLASS varchar(50), IP varchar(20), LOGTIME varchar(20), REMARK varchar(200), ROLENAME varchar(20), primary key (ID));
create table PhoneDistrict (id char(32) not null, VERSION int8 not null, districtNumber varchar(20), range varchar(45000), feeType varchar(20), districtCity varchar(20), districtProvince varchar(20), updateFlg int4, pingyinCity varchar(20), weatherCityCode varchar(20), primary key (id));
create table Weather (id char(32) not null, VERSION int8 not null, date varchar(20), weatherCityCode varchar(20), weatherType varchar(50), high int4, low int4, wind varchar(30), icon varchar(30), isNight bool, issuetime varchar(10), primary key (id));
alter table ContactTag add constraint FK7F280B7A39AFF238 foreign key (createUser) references ContactUser;
