//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1873
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.1873.
// 
namespace BelugaMobile.Db.Xsd
{
    using System;
    using System.Data;
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("userconfig")]
    public partial class userconfig : global::System.Data.DataSet {
        
        private user_configDataTable tableuser_config;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public userconfig() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public user_configDataTable user_config {
            get {
                return this.tableuser_config;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            userconfig cln = ((userconfig)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["user_config"] != null)) {
                    base.Tables.Add(new user_configDataTable(ds.Tables["user_config"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableuser_config = ((user_configDataTable)(base.Tables["user_config"]));
            if ((initTable == true)) {
                if ((this.tableuser_config != null)) {
                    this.tableuser_config.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "userconfig";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/userconfig.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableuser_config = new user_configDataTable();
            base.Tables.Add(this.tableuser_config);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeuser_config() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            userconfig ds = new userconfig();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void user_configRowChangeEventHandler(object sender, user_configRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class user_configDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnuser_id;
            
            private global::System.Data.DataColumn columnimei;
            
            private global::System.Data.DataColumn columnusername;
            
            private global::System.Data.DataColumn columnmobile;
            
            private global::System.Data.DataColumn columnsex;
            
            private global::System.Data.DataColumn columnphoto;
            
            private global::System.Data.DataColumn columnsignature;
            
            private global::System.Data.DataColumn columnhome_tel;
            
            private global::System.Data.DataColumn columnwork_tel;
            
            private global::System.Data.DataColumn columnother_tel;
            
            private global::System.Data.DataColumn columnfax;
            
            private global::System.Data.DataColumn columnperson_email;
            
            private global::System.Data.DataColumn columnwork_email;
            
            private global::System.Data.DataColumn columnother_email;
            
            private global::System.Data.DataColumn columnhome_street;
            
            private global::System.Data.DataColumn columnhome_city;
            
            private global::System.Data.DataColumn columnhome_province;
            
            private global::System.Data.DataColumn columnwork_street;
            
            private global::System.Data.DataColumn columnwork_city;
            
            private global::System.Data.DataColumn columnwork_province;
            
            private global::System.Data.DataColumn columnother_street;
            
            private global::System.Data.DataColumn columnother_city;
            
            private global::System.Data.DataColumn columnother_province;
            
            private global::System.Data.DataColumn columnqq;
            
            private global::System.Data.DataColumn columnmsn;
            
            private global::System.Data.DataColumn columnother_im;
            
            private global::System.Data.DataColumn columnurl;
            
            private global::System.Data.DataColumn columnbirthday;
            
            private global::System.Data.DataColumn columnorg;
            
            private global::System.Data.DataColumn columntitle;
            
            private global::System.Data.DataColumn columnnote;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public user_configDataTable() {
                this.TableName = "user_config";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal user_configDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn user_idColumn {
                get {
                    return this.columnuser_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn imeiColumn {
                get {
                    return this.columnimei;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn usernameColumn {
                get {
                    return this.columnusername;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn mobileColumn {
                get {
                    return this.columnmobile;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sexColumn {
                get {
                    return this.columnsex;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn photoColumn {
                get {
                    return this.columnphoto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn signatureColumn {
                get {
                    return this.columnsignature;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn home_telColumn {
                get {
                    return this.columnhome_tel;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn work_telColumn {
                get {
                    return this.columnwork_tel;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn other_telColumn {
                get {
                    return this.columnother_tel;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn faxColumn {
                get {
                    return this.columnfax;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn person_emailColumn {
                get {
                    return this.columnperson_email;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn work_emailColumn {
                get {
                    return this.columnwork_email;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn other_emailColumn {
                get {
                    return this.columnother_email;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn home_streetColumn {
                get {
                    return this.columnhome_street;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn home_cityColumn {
                get {
                    return this.columnhome_city;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn home_provinceColumn {
                get {
                    return this.columnhome_province;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn work_streetColumn {
                get {
                    return this.columnwork_street;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn work_cityColumn {
                get {
                    return this.columnwork_city;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn work_provinceColumn {
                get {
                    return this.columnwork_province;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn other_streetColumn {
                get {
                    return this.columnother_street;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn other_cityColumn {
                get {
                    return this.columnother_city;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn other_provinceColumn {
                get {
                    return this.columnother_province;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn qqColumn {
                get {
                    return this.columnqq;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn msnColumn {
                get {
                    return this.columnmsn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn other_imColumn {
                get {
                    return this.columnother_im;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn urlColumn {
                get {
                    return this.columnurl;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn birthdayColumn {
                get {
                    return this.columnbirthday;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn orgColumn {
                get {
                    return this.columnorg;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn titleColumn {
                get {
                    return this.columntitle;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn noteColumn {
                get {
                    return this.columnnote;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public user_configRow this[int index] {
                get {
                    return ((user_configRow)(this.Rows[index]));
                }
            }
            
            public event user_configRowChangeEventHandler user_configRowChanging;
            
            public event user_configRowChangeEventHandler user_configRowChanged;
            
            public event user_configRowChangeEventHandler user_configRowDeleting;
            
            public event user_configRowChangeEventHandler user_configRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Adduser_configRow(user_configRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public user_configRow Adduser_configRow(
                        string user_id, 
                        string imei, 
                        string username, 
                        string mobile,
                        string sex, 
                        string photo, 
                        string signature, 
                        string home_tel, 
                        string work_tel, 
                        string other_tel, 
                        string fax, 
                        string person_email, 
                        string work_email, 
                        string other_email, 
                        string home_street, 
                        string home_city, 
                        string home_province, 
                        string work_street, 
                        string work_city, 
                        string work_province, 
                        string other_street, 
                        string other_city, 
                        string other_province, 
                        string qq, 
                        string msn, 
                        string other_im, 
                        string url, 
                        System.DateTime birthday, 
                        string org, 
                        string title, 
                        string note) {
                user_configRow rowuser_configRow = ((user_configRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        user_id,
                        imei,
                        username,
                        mobile,
                        sex,
                        photo,
                        signature,
                        home_tel,
                        work_tel,
                        other_tel,
                        fax,
                        person_email,
                        work_email,
                        other_email,
                        home_street,
                        home_city,
                        home_province,
                        work_street,
                        work_city,
                        work_province,
                        other_street,
                        other_city,
                        other_province,
                        qq,
                        msn,
                        other_im,
                        url,
                        birthday,
                        org,
                        title,
                        note};
                rowuser_configRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowuser_configRow);
                return rowuser_configRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                user_configDataTable cln = ((user_configDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new user_configDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnuser_id = base.Columns["user_id"];
                this.columnimei = base.Columns["imei"];
                this.columnusername = base.Columns["username"];
                this.columnmobile = base.Columns["mobile"];
                this.columnsex = base.Columns["sex"];
                this.columnphoto = base.Columns["photo"];
                this.columnsignature = base.Columns["signature"];
                this.columnhome_tel = base.Columns["home_tel"];
                this.columnwork_tel = base.Columns["work_tel"];
                this.columnother_tel = base.Columns["other_tel"];
                this.columnfax = base.Columns["fax"];
                this.columnperson_email = base.Columns["person_email"];
                this.columnwork_email = base.Columns["work_email"];
                this.columnother_email = base.Columns["other_email"];
                this.columnhome_street = base.Columns["home_street"];
                this.columnhome_city = base.Columns["home_city"];
                this.columnhome_province = base.Columns["home_province"];
                this.columnwork_street = base.Columns["work_street"];
                this.columnwork_city = base.Columns["work_city"];
                this.columnwork_province = base.Columns["work_province"];
                this.columnother_street = base.Columns["other_street"];
                this.columnother_city = base.Columns["other_city"];
                this.columnother_province = base.Columns["other_province"];
                this.columnqq = base.Columns["qq"];
                this.columnmsn = base.Columns["msn"];
                this.columnother_im = base.Columns["other_im"];
                this.columnurl = base.Columns["url"];
                this.columnbirthday = base.Columns["birthday"];
                this.columnorg = base.Columns["org"];
                this.columntitle = base.Columns["title"];
                this.columnnote = base.Columns["note"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnuser_id = new global::System.Data.DataColumn("user_id", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnuser_id);
                this.columnimei = new global::System.Data.DataColumn("imei", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnimei);
                this.columnusername = new global::System.Data.DataColumn("username", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnusername);
                this.columnmobile = new global::System.Data.DataColumn("mobile", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmobile);
                this.columnsex = new global::System.Data.DataColumn("sex", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsex);
                this.columnphoto = new global::System.Data.DataColumn("photo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnphoto);
                this.columnsignature = new global::System.Data.DataColumn("signature", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsignature);
                this.columnhome_tel = new global::System.Data.DataColumn("home_tel", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhome_tel);
                this.columnwork_tel = new global::System.Data.DataColumn("work_tel", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnwork_tel);
                this.columnother_tel = new global::System.Data.DataColumn("other_tel", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnother_tel);
                this.columnfax = new global::System.Data.DataColumn("fax", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfax);
                this.columnperson_email = new global::System.Data.DataColumn("person_email", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnperson_email);
                this.columnwork_email = new global::System.Data.DataColumn("work_email", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnwork_email);
                this.columnother_email = new global::System.Data.DataColumn("other_email", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnother_email);
                this.columnhome_street = new global::System.Data.DataColumn("home_street", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhome_street);
                this.columnhome_city = new global::System.Data.DataColumn("home_city", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhome_city);
                this.columnhome_province = new global::System.Data.DataColumn("home_province", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhome_province);
                this.columnwork_street = new global::System.Data.DataColumn("work_street", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnwork_street);
                this.columnwork_city = new global::System.Data.DataColumn("work_city", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnwork_city);
                this.columnwork_province = new global::System.Data.DataColumn("work_province", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnwork_province);
                this.columnother_street = new global::System.Data.DataColumn("other_street", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnother_street);
                this.columnother_city = new global::System.Data.DataColumn("other_city", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnother_city);
                this.columnother_province = new global::System.Data.DataColumn("other_province", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnother_province);
                this.columnqq = new global::System.Data.DataColumn("qq", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnqq);
                this.columnmsn = new global::System.Data.DataColumn("msn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmsn);
                this.columnother_im = new global::System.Data.DataColumn("other_im", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnother_im);
                this.columnurl = new global::System.Data.DataColumn("url", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnurl);
                this.columnbirthday = new global::System.Data.DataColumn("birthday", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbirthday);
                this.columnorg = new global::System.Data.DataColumn("org", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnorg);
                this.columntitle = new global::System.Data.DataColumn("title", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntitle);
                this.columnnote = new global::System.Data.DataColumn("note", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnote);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public user_configRow Newuser_configRow() {
                return ((user_configRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new user_configRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(user_configRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.user_configRowChanged != null)) {
                    this.user_configRowChanged(this, new user_configRowChangeEvent(((user_configRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.user_configRowChanging != null)) {
                    this.user_configRowChanging(this, new user_configRowChangeEvent(((user_configRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.user_configRowDeleted != null)) {
                    this.user_configRowDeleted(this, new user_configRowChangeEvent(((user_configRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.user_configRowDeleting != null)) {
                    this.user_configRowDeleting(this, new user_configRowChangeEvent(((user_configRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Removeuser_configRow(user_configRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                userconfig ds = new userconfig();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "user_configDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class user_configRow : global::System.Data.DataRow {
            
            private user_configDataTable tableuser_config;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal user_configRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableuser_config = ((user_configDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string user_id {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.user_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'user_id\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.user_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string imei {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.imeiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'imei\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.imeiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string username {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.usernameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'username\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.usernameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string mobile {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.mobileColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'mobile\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.mobileColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string sex {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.sexColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sex\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.sexColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string photo {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.photoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'photo\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.photoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string signature {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.signatureColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'signature\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.signatureColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string home_tel {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.home_telColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'home_tel\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.home_telColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string work_tel {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.work_telColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'work_tel\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.work_telColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string other_tel {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.other_telColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'other_tel\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.other_telColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string fax {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.faxColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'fax\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.faxColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string person_email {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.person_emailColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'person_email\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.person_emailColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string work_email {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.work_emailColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'work_email\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.work_emailColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string other_email {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.other_emailColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'other_email\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.other_emailColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string home_street {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.home_streetColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'home_street\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.home_streetColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string home_city {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.home_cityColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'home_city\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.home_cityColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string home_province {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.home_provinceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'home_province\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.home_provinceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string work_street {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.work_streetColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'work_street\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.work_streetColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string work_city {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.work_cityColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'work_city\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.work_cityColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string work_province {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.work_provinceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'work_province\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.work_provinceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string other_street {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.other_streetColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'other_street\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.other_streetColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string other_city {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.other_cityColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'other_city\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.other_cityColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string other_province {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.other_provinceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'other_province\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.other_provinceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string qq {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.qqColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'qq\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.qqColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string msn {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.msnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'msn\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.msnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string other_im {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.other_imColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'other_im\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.other_imColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string url {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.urlColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'url\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.urlColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime birthday {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableuser_config.birthdayColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'birthday\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.birthdayColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string org {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.orgColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'org\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.orgColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string title {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.titleColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'title\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.titleColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string note {
                get {
                    try {
                        return ((string)(this[this.tableuser_config.noteColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'note\' in table \'user_config\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuser_config.noteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isuser_idNull() {
                return this.IsNull(this.tableuser_config.user_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setuser_idNull() {
                this[this.tableuser_config.user_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsimeiNull() {
                return this.IsNull(this.tableuser_config.imeiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetimeiNull() {
                this[this.tableuser_config.imeiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsusernameNull() {
                return this.IsNull(this.tableuser_config.usernameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetusernameNull() {
                this[this.tableuser_config.usernameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsmobileNull() {
                return this.IsNull(this.tableuser_config.mobileColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetmobileNull() {
                this[this.tableuser_config.mobileColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IssexNull() {
                return this.IsNull(this.tableuser_config.sexColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetsexNull() {
                this[this.tableuser_config.sexColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsphotoNull() {
                return this.IsNull(this.tableuser_config.photoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetphotoNull() {
                this[this.tableuser_config.photoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IssignatureNull() {
                return this.IsNull(this.tableuser_config.signatureColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetsignatureNull() {
                this[this.tableuser_config.signatureColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ishome_telNull() {
                return this.IsNull(this.tableuser_config.home_telColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Sethome_telNull() {
                this[this.tableuser_config.home_telColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iswork_telNull() {
                return this.IsNull(this.tableuser_config.work_telColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setwork_telNull() {
                this[this.tableuser_config.work_telColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isother_telNull() {
                return this.IsNull(this.tableuser_config.other_telColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setother_telNull() {
                this[this.tableuser_config.other_telColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsfaxNull() {
                return this.IsNull(this.tableuser_config.faxColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetfaxNull() {
                this[this.tableuser_config.faxColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isperson_emailNull() {
                return this.IsNull(this.tableuser_config.person_emailColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setperson_emailNull() {
                this[this.tableuser_config.person_emailColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iswork_emailNull() {
                return this.IsNull(this.tableuser_config.work_emailColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setwork_emailNull() {
                this[this.tableuser_config.work_emailColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isother_emailNull() {
                return this.IsNull(this.tableuser_config.other_emailColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setother_emailNull() {
                this[this.tableuser_config.other_emailColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ishome_streetNull() {
                return this.IsNull(this.tableuser_config.home_streetColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Sethome_streetNull() {
                this[this.tableuser_config.home_streetColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ishome_cityNull() {
                return this.IsNull(this.tableuser_config.home_cityColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Sethome_cityNull() {
                this[this.tableuser_config.home_cityColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ishome_provinceNull() {
                return this.IsNull(this.tableuser_config.home_provinceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Sethome_provinceNull() {
                this[this.tableuser_config.home_provinceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iswork_streetNull() {
                return this.IsNull(this.tableuser_config.work_streetColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setwork_streetNull() {
                this[this.tableuser_config.work_streetColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iswork_cityNull() {
                return this.IsNull(this.tableuser_config.work_cityColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setwork_cityNull() {
                this[this.tableuser_config.work_cityColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iswork_provinceNull() {
                return this.IsNull(this.tableuser_config.work_provinceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setwork_provinceNull() {
                this[this.tableuser_config.work_provinceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isother_streetNull() {
                return this.IsNull(this.tableuser_config.other_streetColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setother_streetNull() {
                this[this.tableuser_config.other_streetColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isother_cityNull() {
                return this.IsNull(this.tableuser_config.other_cityColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setother_cityNull() {
                this[this.tableuser_config.other_cityColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isother_provinceNull() {
                return this.IsNull(this.tableuser_config.other_provinceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setother_provinceNull() {
                this[this.tableuser_config.other_provinceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsqqNull() {
                return this.IsNull(this.tableuser_config.qqColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetqqNull() {
                this[this.tableuser_config.qqColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsmsnNull() {
                return this.IsNull(this.tableuser_config.msnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetmsnNull() {
                this[this.tableuser_config.msnColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isother_imNull() {
                return this.IsNull(this.tableuser_config.other_imColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setother_imNull() {
                this[this.tableuser_config.other_imColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsurlNull() {
                return this.IsNull(this.tableuser_config.urlColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SeturlNull() {
                this[this.tableuser_config.urlColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsbirthdayNull() {
                return this.IsNull(this.tableuser_config.birthdayColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetbirthdayNull() {
                this[this.tableuser_config.birthdayColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsorgNull() {
                return this.IsNull(this.tableuser_config.orgColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetorgNull() {
                this[this.tableuser_config.orgColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IstitleNull() {
                return this.IsNull(this.tableuser_config.titleColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SettitleNull() {
                this[this.tableuser_config.titleColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsnoteNull() {
                return this.IsNull(this.tableuser_config.noteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetnoteNull() {
                this[this.tableuser_config.noteColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        public class user_configRowChangeEvent : global::System.EventArgs {
            
            private user_configRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public user_configRowChangeEvent(user_configRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public user_configRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace userconfigUtil {
    using System;
    using System.Data;
    
    
    public partial class DesignerUtil {
        
        public static bool IsDesignTime() {
            // Determine if this instance is running against .NET Framework by using the MSCoreLib PublicKeyToken
            System.Reflection.Assembly mscorlibAssembly = typeof(int).Assembly;
            if ((mscorlibAssembly != null)) {
                if (mscorlibAssembly.FullName.ToUpper().EndsWith("B77A5C561934E089")) {
                    return true;
                }
            }
            return false;
        }
        
        public static bool IsRunTime() {
            // Determine if this instance is running against .NET Compact Framework by using the MSCoreLib PublicKeyToken
            System.Reflection.Assembly mscorlibAssembly = typeof(int).Assembly;
            if ((mscorlibAssembly != null)) {
                if (mscorlibAssembly.FullName.ToUpper().EndsWith("969DB8053D3322AC")) {
                    return true;
                }
            }
            return false;
        }
    }
}
